#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

setmonitors.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          10

bspc config normal_border_color  	#000055
bspc config focused_border_color 	#AAAAFF
bspc config split_ratio          	0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config single_monocle		true
bspc config pointer_modifier     	mod4
bspc config focus_follows_pointer	true

bspc rule -a firefox desktop='^3'

bspc rule -a qemu-system-x86_64 desktop='^7'

bspc rule -a Steam desktop='^10'

